version: 2.1

executors:
  java-executor:
    docker:
      - image: maven:3.8.4-openjdk-11  # Using Maven and OpenJDK 11 for Java projects
    working_directory: ~/repo  # Specifies the working directory inside the container

jobs:
  build:
    executor: java-executor  # Use the executor defined above
    steps:
      - checkout  # Checks out your code from GitHub
      - run:
          name: Set up Maven and Install Dependencies
          command: mvn clean install  # Install dependencies and compile the code
      - run:
          name: Run Tests
          command: mvn test  # Run all tests
      - run:
          name: Generate Test Report
          command: mvn surefire-report:report  # Generate Surefire test reports

  deploy:
    docker:
      - image: maven:3.8.4-openjdk-11  # Using the same Docker image for consistency
    steps:
      - checkout
      - run:
          name: Deploy (Optional)
          command: echo "Deploying application"

workflows:
  version: 2
  build_and_deploy:  # Define a workflow to run build and deploy jobs in sequence
    jobs:
      - build

